version: '3.3'

services:
  pgadmin:
    image: dpage/pgadmin4:6.9
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@pgadmin.com"
      PGADMIN_DEFAULT_PASSWORD: "password"
      PGADMIN_LISTEN_PORT: "15432"
    ports:
      - "127.0.0.1:15432:15432"

  postgres:
    image: postgres:14.4
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "aban"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"

  redis:
    image: redis:6.2.7
    container_name: redis
    restart: always
    volumes:
      - redis-data:/data
    ports:
      - '127.0.0.1:6379:6379'


volumes:
  postgres-data:
    external: True
  redis-data:
    external: True
