from os import getenv

PLATFORM = getenv("PLATFORM", "local")
BACKEND_REDIS_HOST = getenv("BACKEND_REDIS_HOST", "127.0.0.1")
BACKEND_REDIS_PORT = getenv("BACKEND_REDIS_PORT", "6379")

BACKEND_POSTGRES_HOST = getenv("BACKEND_POSTGRES_HOST", "127.0.0.1")
BACKEND_POSTGRES_PORT = getenv("BACKEND_POSTGRES_PORT", "5432")
BACKEND_POSTGRES_NAME = getenv("BACKEND_POSTGRES_NAME", "aban")
BACKEND_POSTGRES_USERNAME = getenv("BACKEND_POSTGRES_USERNAME", "postgres")
BACKEND_POSTGRES_PASSWORD = getenv("BACKEND_POSTGRES_PASSWORD", "postgres")


SENTRY_DSN_ADDRESS = getenv(
    "SENTRY_DSN_ADDRESS", "http://e7ff4e71994848e595e83d457af2579a@sentry:9000/2"
)


USER_CLIENT_TYPE = 1
TOKEN_ID = "p1"
KEY_ID = "p2"
CLIENT_TYPE = "p3"
CLIENT_TYPES = [USER_CLIENT_TYPE]
PAYLOAD_PARAMETERS = {TOKEN_ID, KEY_ID, CLIENT_TYPE}


REDIS_DEFAULT = "0"
REDIS_RATELIMIT = "1"
REDIS_TOKENS = "2"
REDIS_KEYS = "3"
REDIS_COIN_INFO = "4"
REDIS_CACHE_LOCK = "5"
REDIS_CELERY_BROKER = "6"
REDIS_CELERY_BACKEND = "7"
REDIS_CHANNEL_LAYER = "8"


SWAGGER_URL_MAP = {
    "local": "http://127.0.0.1:8000",
    "production": "https://api.abandev.ir",
}
SWAGGER_URL = SWAGGER_URL_MAP.get(PLATFORM, None)

VALID_QUOTE_ASSETS = ["USDT", "IRT"]
