# Generated by Django 4.0.8 on 2024-08-21 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=15, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('persian_name', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('trade_fee', models.DecimalField(decimal_places=5, max_digits=10)),
                ('global_fee', models.DecimalField(decimal_places=5, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='AssetPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_order_value', models.DecimalField(decimal_places=20, max_digits=40, null=True)),
                ('max_order_value', models.DecimalField(decimal_places=20, max_digits=40, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('base_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_assets', to='exchange.asset')),
            ],
        ),
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True)),
                ('exchange_type', models.IntegerField(choices=[(1, 'aban'), (2, 'binance')])),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=20, max_digits=40)),
                ('side', models.IntegerField(choices=[('buy', 1), ('sell', 2)])),
                ('status', models.IntegerField(choices=[('created', 1), ('processing', 2), ('filled', 3), ('success', 4), ('failed', 5), ('unknown', 6)], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('asset_pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='exchange.assetpair')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='user.user')),
            ],
        ),
        migrations.CreateModel(
            name='CryptoAsset',
            fields=[
                ('asset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='exchange.asset')),
                ('buy', models.BooleanField(default=True)),
                ('sell', models.BooleanField(default=True)),
                ('order_market', models.BooleanField(default=True)),
            ],
            bases=('exchange.asset',),
        ),
        migrations.CreateModel(
            name='FiatAsset',
            fields=[
                ('asset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='exchange.asset')),
                ('is_main', models.BooleanField(default=False)),
            ],
            bases=('exchange.asset',),
        ),
        migrations.CreateModel(
            name='ExchangeOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[('created', 1), ('processing', 2), ('success', 3), ('failed', 4), ('unknown', 5)])),
                ('result', models.JSONField(null=True)),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='exchange.exchange')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_order', to='exchange.order')),
            ],
        ),
        migrations.AddField(
            model_name='assetpair',
            name='exchange',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairs', to='exchange.exchange'),
        ),
        migrations.AddField(
            model_name='assetpair',
            name='quote_asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_assets', to='exchange.asset'),
        ),
        migrations.CreateModel(
            name='StableAsset',
            fields=[
                ('cryptoasset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='exchange.cryptoasset')),
                ('is_main', models.BooleanField(default=False)),
            ],
            bases=('exchange.cryptoasset',),
        ),
        migrations.CreateModel(
            name='MockOrder',
            fields=[
                ('order_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='exchange.order')),
                ('value', models.DecimalField(decimal_places=20, max_digits=40)),
                ('mock_status', models.IntegerField(choices=[(1, 'waiting'), (2, 'aggregating'), (3, 'done')], default=1)),
                ('aggregated_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_orders', to='exchange.order')),
            ],
            bases=('exchange.order',),
        ),
        migrations.AlterUniqueTogether(
            name='assetpair',
            unique_together={('base_asset', 'quote_asset')},
        ),
        migrations.CreateModel(
            name='StableAssetPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('fiat_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stable_coins', to='exchange.fiatasset')),
                ('stable_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price', to='exchange.stableasset')),
            ],
            options={
                'unique_together': {('stable_asset', 'fiat_asset')},
            },
        ),
    ]
