# Generated by Django 4.0.8 on 2024-08-21 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='global_fee',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='trade_fee',
        ),
        migrations.AlterField(
            model_name='stableassetprice',
            name='price',
            field=models.DecimalField(decimal_places=20, max_digits=40),
        ),
    ]
