# Generated by Django 4.0.8 on 2024-08-21 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SystemUser',
        ),
    ]
