# Generated by Django 4.0.8 on 2024-08-21 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exchange', '0001_initial'),
        ('user', '0001_initial'),
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfo',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='exchange.asset'),
        ),
        migrations.AddField(
            model_name='portfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfo', to='user.user'),
        ),
        migrations.AlterUniqueTogether(
            name='portfo',
            unique_together={('user', 'asset')},
        ),
    ]
