name: Django CI

on:
  push:
    branches:
      - '**'  
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
          python-version: ['3.10.5']

    services:
      postgres:
        image: postgres:14.4
        env:
          POSTGRES_DB: alinance
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - "127.0.0.1:5432:5432"
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      redis:
        image: redis:6.2.7
        options: --health-cmd "redis-cli ping" --health-interval 10s --health-timeout 5s --health-retries 5
        ports:
          - "127.0.0.1:6379:6379"

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Migrate Models
      run: |
        python ./manage.py makemigrations
        python ./manage.py migrate
        python ./manage.py submit_test_data

    - name: Run Tests
      env:
        PLATFORM: "ci/cd"
      run: |
        python ./manage.py test */tests/
